// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace MauiEssentials
{
    internal sealed partial class Vsix
    {
        public const string Id = "MauiEssentials.57ba0edc-b007-4755-961f-d4e52848b36a";
        public const string Name = ".NET MAUI Essentials";
        public const string Description = @"A collection of Visual Studio extensions to help with .NET MAUI development";
        public const string Language = "en-US";
        public const string Version = "1.4.0";
        public const string Author = "Matt Lacey";
        public const string Tags = "";
    }
}
